---
- name: Unzip applicaton
  unarchive:
    src: twcloud.zip
    dest: /opt/twcloud

- name: Update config file
  lineinfile:
    path: /opt/twcloud/TWCloud/configuration/application.conf
    regexp: '^SELINUX='
    line: 'SELINUX=enforcing'
  loop_with:
  - { search: '^hostname=', replace: "hostname={{ inventory_hostname }}" }
  - { search: '^seed-nodes = ', replace: "seed-nodes = [\"akka.tcp://twcloud@{{ inventory_hostname }}:2552\"]" }
  - { search: '^host = ', replace: "host = {{ inventory_hostname }}" }

- name: Add ENV file
  copy:
    dest: /etc/twcloud/twcloud-env
    mode: 0600
    owner: root
    content: |
      TWCLOUD_HOME=/opt/twcloud/TWCloud/ 
      TWCLOUD_OWNR=root
      JAVA_HOME=/usr/java/jdk1.8.0_112/ TWCLOUD_HOME=/opt/twcloud/TWCloud/ 

- name: Install TWCloud Service
  copy:
    dest: /etc/init.d
    src: /opt/twcloud/TWCloud/scripts/linux/twcloud-svc
    remote_src: yes
    mode: 0755
    owner: root

- name: Enable TWCloud Service
  service:
    name: twcloud
    enabled: yes
    state: started