---
- name: Install TWCloud Prerequisites
  package:
    name:
    - dejavu-serif-fonts
    # - tomcat-native
    state: present

- name: Setup twcloud User
  user:
    name: twcloud
    comment: TeamWork Cloud Admin user
    state: present

- name: Check that the installer exists
  stat:
    path: /tmp/twcloud_190_sp4_installer_linux64.bin
  register: twcloud_installer_file

- name: Get twcloud Installer
  get_url:
    dest: /tmp
    url: http://download1.nomagic.com/twcloud190sp4/twcloud_190_sp4_installer_linux64.bin
    mode: 0755
  when: not twcloud_installer_file.stat.exists

- name: Install TeamWork Cloud
  command: |
    /tmp/twcloud_190_sp4_installer_linux64.bin \
    -i silent \
    -DUSER_INSTALL_DIR="/opt/local/TeamworkCloud" \
    -DLOCAL_IP="{{ ansible_default_ipv4.address }}" \
    -DCLUSTER_SEED_NODE="{{ ansible_default_ipv4.address }}" \
    -DTWCLOUD_OWNR="twcloud" \
    -DTWCLOUD_JAVA_HOME="/etc/alternatives/jre_1.8.0"
  args:
    creates: /opt/local/TeamworkCloud/twcloud
  register: twcloud_install
  failed_when: 
  - twcloud_install.stderr is defined
  - twcloud_install.stderr != ""

- name: Create ENV file
  copy:
    src: twcloud.env
    dest: /etc/twcloud/twcloud-env

- name: Create .twcloud Dir
  file:
    path: /home/twcloud/.twcloud/19.0/workspace/tmp
    state: directory

- name: Create PID Dir
  file:
    path: /var/run/twcloud
    state: directory

- name: Create Log Dir
  file:
    path: /var/log/twcloud/
    state: directory

- name: Set Directory Perms
  file:
    path: "{{ dir }}"
    recurse: yes
    owner: twcloud
    group: twcloud
    state: directory
    mode: 0755
  loop_control:
    loop_var: dir
  loop:
  - /home/twcloud/.twcloud/
  - /var/run/twcloud/
  - /var/log/twcloud/
  - /opt/local/TeamworkCloud/

- name: Update twcloud.ini
  lineinfile:
    path: /opt/local/TeamworkCloud/twcloud.ini
    state: present
    regexp: -Djava.io.tmpdir=/tmp
    line: -Djava.io.tmpdir=/home/twcloud/.twcloud/19.0/workspace/tmp

- name: Create Startup Script
  copy:
    src: twcloud-run.sh
    dest: /opt/local/TeamworkCloud/scripts/linux/twcloud-run
    owner: twcloud
    group: twcloud
    mode: 0755

- name: Create twcloud Firewall Service
  copy:
    src: twcloud.xml
    dest: /etc/firewalld/services/twcloud.xml
  register: twcloud_firewall_svc

- name: reload firewalld service
  systemd:
    name: firewalld
    state: reloaded
  when: twcloud_firewall_svc is changed

- name: Open Firewall Ports
  firewalld:
    state: enabled
    service: twcloud
    immediate: yes
    permanent: yes

- name: Increase file limits for twcloud user
  lineinfile:
    path: /etc/security/limits.d/twcloud.conf
    create: yes
    state: present
    line: twcloud - nofile 50000 

- name: Sysctl Performance Tuning
  sysctl:
    name: "{{ sysctl_setting.name }}"
    reload: yes
    state: present
    value: "{{ sysctl_setting.value }}"
  loop_control:
    loop_var: sysctl_setting
  loop:
  - { name: 'net.core.rmem_max', value: '16777216' }
  - { name: 'net.core.wmem_max', value: '16777216' }
  - { name: 'net.core.optmem_max', value: '40960' }
  - { name: 'net.core.default_qdisc', value: 'fq' }
  - { name: 'net.core.somaxconn', value: '4096' }
  - { name: 'net.ipv4.conf.all.arp_notify ', value: ' 1' }
  - { name: 'net.ipv4.tcp_keepalive_time', value: '60' }
  - { name: 'net.ipv4.tcp_keepalive_probes', value: '3' }
  - { name: 'net.ipv4.tcp_keepalive_intvl', value: '10' }
  - { name: 'net.ipv4.tcp_mtu_probing', value: '1' }
  - { name: 'net.ipv4.tcp_rmem', value: '4096 12582912 16777216' }
  - { name: 'net.ipv4.tcp_wmem', value: '4096 12582912 16777216' }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: '8096' }
  - { name: 'net.ipv4.tcp_slow_start_after_idle ', value: ' 0' }
  - { name: 'net.ipv4.tcp_tw_reuse ', value: ' 1' }
  - { name: 'vm.max_map_count ', value: ' 1048575' }
  - { name: 'vm.swappiness ', value: ' 0' }
  - { name: 'vm.dirty_background_ratio', value: '5' }
  - { name: 'vm.dirty_ratio', value: '80' }
  - { name: 'vm.dirty_expire_centisecs ', value: ' 12000' }

- name: Create tunedisk.sh Script
  copy:
    dest: /home/twcloud/tunedisk.sh
    src: tunedisk.sh
    mode: 0755
  register: create_tunedisk

- name: Add tunedisk.sh to Server Startup
  lineinfile:
    path: /etc/rc.local
    insertafter: EOF
    mode: 0755
    line: /home/twcloud/tunedisk.sh

- name: Execute tunedisk.sh
  command: /home/twcloud/tunedisk.sh
  register: tunedisk_result
  when: create_tunedisk is changed

- name: Update Application Config
  replace:
    path: /opt/local/TeamworkCloud/configuration/application.conf
    regexp: '"localhost"'
    replace: '"{{ ansible_default_ipv4.address }}"'
  notify:
  - restart_twcloud

- name: Update AuthServer Properties
  replace:
    path: /opt/local/TeamworkCloud/AuthServer/config/authserver.properties
    regexp: "{{ auth_conf_item.regex }}"
    replace: '{{ auth_conf_item.value }}'
  loop_control:
    loop_var: auth_conf_item
  loop:
  - { regex: '(server\.public\.host=).*', value: '\g<1>{{ teamwork_fqdn }}' }
  - { regex: '(twc\.server\.host=).*', value: '\g<1>{{ ansible_default_ipv4.address }}' }
  - { regex: '(cassandra\.contactPoints=).*', value: '\g<1>{{ ansible_default_ipv4.address }}' }
  - { regex: '(authentication\.redirect\.uri\.whitelist=).*', value: '\g<1>https://{{ ansible_default_ipv4.address }}:8443/webapp/,https://{{ teamwork_fqdn }}:8443/webapp/,https://md_redirect' }
  notify:
  - restart_authserver

- name: Update WebApp Properties
  replace:
    path: /opt/local/TeamworkCloud/WebAppPlatform/shared/conf/webappplatform.properties
    regexp: "{{ auth_conf_item.regex }}"
    replace: '{{ auth_conf_item.value }}'
  loop_control:
    loop_var: auth_conf_item
  loop:
  - { regex: '(authentication\.server\.uri=).*', value: '\g<1>https://{{ teamwork_fqdn }}:8555/authentication' }
  - { regex: '(twc\.url=).*', value: '\g<1>https://{{ teamwork_fqdn }}:8111/authentication' }
  - { regex: '(flexnet\.server\.name=).*', value: '\g<1>{{ ansible_default_ipv4.address }}' }
  notify:
  - restart_webapp

- name: Update Password - TWCloud
  no_log: true
  replace:
    path: /opt/local/TeamworkCloud/configuration/application.conf
    regexp: '(^\s*authentication-password = ").*'
    replace: '\g<1>{{ auth_pass }}"'
  notify:
  - restart_twcloud

- name: Update Password - AuthServer
  no_log: true
  replace:
    path: /opt/local/TeamworkCloud/AuthServer/config/authserver.properties
    regexp: '.*(authentication.client.secret=).*'
    replace: '\g<1>{{ auth_pass }}'
  notify:
  - restart_authserver

- name: Update Passwords - WebApp
  no_log: true
  replace:
    path: /opt/local/TeamworkCloud/WebAppPlatform/shared/conf/webappplatform.properties
    regexp: "{{ web_conf_item.regex }}"
    replace: "{{ web_conf_item.value }}"
  loop_control:
    loop_var: web_conf_item
  loop:
  - { regex: '(twc.admin.username=).*', value: '\g<1>{{ admin_user }}' }
  - { regex: '(twc.admin.password=).*', value: '\g<1>{{ admin_pass }}' }
  - { regex: '.*(authentication.client.secret=).*', value: '\g<1>{{ auth_pass }}' }
  notify:
  - restart_webapp

- name: Install and Enable Services
  include_tasks:
    file: install_service.yml
  loop_control:
    loop_var: service_name
  loop:
  - authserver
  - twcloud
  - webapp