cassandra_cluster_name: Standalone
cassandra_seed: "{{ ansible_default_ipv4.address }}"
cassandra_repo_apache_release: 311x
cassandra_configuration:
  cluster_name: "{{ cassandra_cluster_name }}"
  num_tokens: 256
  authenticator: AllowAllAuthenticator
  authorizer: AllowAllAuthorizer
  commitlog_directory: /logs/commitlog
  commitlog_sync: periodic
  commitlog_sync_period_in_ms: 10000
  data_file_directories:
    - /data/data
  endpoint_snitch: GossipingPropertyFileSnitch
  hints_directory: /data/hints
  listen_address: "{{ ansible_default_ipv4.address }}"
  partitioner: org.apache.cassandra.dht.Murmur3Partitioner
  saved_caches_directory: /data/saved_caches
  seed_provider:
    - class_name: "org.apache.cassandra.locator.SimpleSeedProvider"
      parameters:
        - seeds: "{{ cassandra_seed }}"
  start_native_transport: true
  hinted_handoff_enabled: true
  hinted_handoff_throttle_in_kb: 1024
  max_hints_delivery_threads: 2
  hints_flush_period_in_ms: 10000
  max_hints_file_size_in_mb: 128
  batchlog_replay_throttle_in_kb: 1024
  role_manager: CassandraRoleManager
  roles_validity_in_ms: 2000
  permissions_validity_in_ms: 2000
  credentials_validity_in_ms: 2000
  cdc_enabled: false
  disk_failure_policy: stop
  commit_failure_policy: stop
  prepared_statements_cache_size_mb:
  thrift_prepared_statements_cache_size_mb:
  key_cache_size_in_mb:
  key_cache_save_period: 14400
  row_cache_size_in_mb: 0
  row_cache_save_period: 0
  counter_cache_size_in_mb:
  counter_cache_save_period: 7200
  commitlog_segment_size_in_mb: 192
  concurrent_reads: 32
  concurrent_writes: 32
  concurrent_counter_writes: 32
  concurrent_materialized_view_writes: 32
  memtable_allocation_type: heap_buffers
  commitlog_total_space_in_mb: 8192
  index_summary_capacity_in_mb:
  index_summary_resize_interval_in_minutes: 60
  trickle_fsync: false
  trickle_fsync_interval_in_kb: 10240
  storage_port: 7000
  ssl_storage_port: 7001
  native_transport_port: 9042
  start_rpc: true
  rpc_address: 0.0.0.0
  rpc_port: 9160
  broadcast_rpc_address: 10.0.2.15
  rpc_keepalive: true
  rpc_server_type: sync
  thrift_framed_transport_size_in_mb: 100
  incremental_backups: false
  snapshot_before_compaction: false
  auto_snapshot: true
  column_index_size_in_kb: 64
  column_index_cache_size_in_kb: 2
  compaction_throughput_mb_per_sec: 16
cassandra_configure_apache_repo: true
cassandra_directories:
  root:
    group: cassandra
    mode: "0755"
    owner: cassandra
    paths:
      - /data
      - /logs
  data:
    paths:
      - /data
      - /logs
      - /logs/commitlog
      - /data/data
      - /data/hints
      - /data/saved_caches
cassandra_regex_replacements:
- path: cassandra-env.sh
  line: 'MAX_HEAP_SIZE="{{ cassandra_max_heapsize_mb }}M"'
  regexp: '^#MAX_HEAP_SIZE="4G"'
- path: cassandra-env.sh
  line: 'HEAP_NEWSIZE="{{ cassandra_heap_new_size_mb }}M"'
  regexp: '^#HEAP_NEWSIZE="800M"'
- path: cassandra-rackdc.properties
  line: 'dc=DC1'
  regexp: '^dc='
- path: cassandra-rackdc.properties
  line: 'rack=RACK1'
  regexp: '^rack='
